"use client";
import { ChakraProvider, Flex, chakra } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children}: any) {
  return (
    <html lang="en">
          <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>

      <body className={inter.className}>
        
       
        <ChakraProvider>
        <Flex>
        <Navbar />
        <main>{children}</main>
        </Flex>
        </ChakraProvider>

          
      </body>
    </html>
  );
}
