"use client";
import { ChakraProvider, Flex, chakra } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { getCookie } from "cookies-next";
import { useEffect } from "react";
import { useRouter } from "next/navigation";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children}: any) {
  const router = useRouter();
  const session = getCookie("session");

  useEffect(()=> {
    if (!session) {
      router.replace('/')
    }
  }, [])

  const queryClient = new QueryClient()

  
  return (
    <html lang="en" suppressHydrationWarning>
          <head> 
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" sizes="any" />      
        </head>

      <body className={inter.className}>
        <ChakraProvider>
        <QueryClientProvider client={queryClient}>
          <main>{children}</main>
        </QueryClientProvider>
        </ChakraProvider>

          
      </body>
    </html>
  );
}
